# Generated by Django 3.0.2 on 2020-01-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogName', models.CharField(max_length=100)),
                ('blogEmail', models.CharField(max_length=100)),
                ('blogSubject', models.CharField(max_length=100)),
                ('blogMessage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsName', models.CharField(max_length=100)),
                ('newsEmail', models.CharField(max_length=100)),
            ],
        ),
    ]
