# Generated by Django 3.0.2 on 2020-02-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_commentform_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_img', models.FileField(upload_to='pics')),
                ('portfolio_desc', models.CharField(max_length=10)),
                ('portfolio_para', models.CharField(max_length=255)),
            ],
        ),
    ]
