# Generated by Django 3.0.2 on 2020-02-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200201_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolioDesc',
            field=models.CharField(max_length=255),
        ),
    ]
