# Generated by Django 3.0.2 on 2020-02-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200201_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='conComment',
            new_name='contactComment',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='conEmail',
            new_name='contactEmail',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='conName',
            new_name='contactName',
        ),
    ]
