# Generated by Django 3.0.2 on 2020-02-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20200202_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='contactComment',
            new_name='conComment',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='contactEmail',
            new_name='conEmail',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='contactName',
            new_name='conName',
        ),
    ]
