# Generated by Django 3.0.2 on 2020-02-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200202_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_work', models.CharField(max_length=255)),
                ('about_para', models.TextField()),
                ('about_parafoot', models.TextField()),
                ('aboutimg', models.FileField(upload_to='pics')),
            ],
        ),
    ]
