# Generated by Django 3.0.2 on 2020-02-02 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_parabody',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
