# Generated by Django 3.0.2 on 2020-02-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_about_about_parabody'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=100)),
                ('view', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('pic', models.FileField(upload_to='pics')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='pics')),
                ('title', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('facebook', models.TextField()),
                ('twitter', models.TextField()),
                ('insta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='pics')),
                ('title', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=100)),
                ('star1', models.BooleanField()),
                ('star2', models.BooleanField()),
                ('star3', models.BooleanField()),
                ('star4', models.BooleanField()),
                ('star5', models.BooleanField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolname', models.CharField(max_length=100)),
                ('toollist', models.IntegerField(verbose_name=3)),
                ('toolvalue', models.IntegerField(verbose_name=3)),
            ],
        ),
    ]
