# Generated by Django 3.0.2 on 2020-02-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_blog_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_details',
            new_name='blog_detailsdesc',
        ),
    ]
