# Generated by Django 3.0.2 on 2020-02-06 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20200206_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_detailsdesc',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
