# Generated by Django 3.0.2 on 2020-02-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20200206_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='view',
        ),
    ]
