# Generated by Django 3.0.2 on 2020-02-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_remove_blog_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blog_desc',
        ),
    ]
