# Generated by Django 3.0.2 on 2020-02-11 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0017_ads_category_detail_post_category_sidebar_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_desc',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
